### ISSUE TITLE
Allow specifying the gpt model

### ISSUE THREAD

**Issue by PaulWoitaschek** [cycneuramus/signal-aichat#15]
I'd like to use gpt4. Currently, gpt3 is hardcoded https://github.com/cycneuramus/signal-aichat/blob/cf05eaf8dee951d68d1f5509d39568b2b343f0bd/ai.py#L132

It would be great to have an option to select which model to use.

**Comment by cycneuramus** [comment]
Should be fixed in 0.6.0

**Comment by PaulWoitaschek** [comment]
😢 That could have been my first python PR ^^

thanks!

**Comment by PaulWoitaschek** [comment]
@cycneuramus 

Does it deploy automatically? A compose pull isn't fetching anything and it seems nothing is deployed in ghrc
https://github.com/cycneuramus/signal-aichat/pkgs/container/signal-aichat/versions?filters%5Bversion_type%5D=tagged

**Comment by cycneuramus** [comment]
It should deploy automatically, but it seems broken ATM. I'll take a look as soon as I have time.

**Comment by cycneuramus** [comment]
The new version should be available now on the `master` tag (`docker pull ghcr.io/cycneuramus/signal-aichat:master`)

**Comment by PaulWoitaschek** [comment]
Thanks. Should we update the compose file to point to that? Right now with what's recommended in the compose file it errors with
>  Head "https://registry.gitlab.com/v2/signald/signald/manifests/latest": received unexpected HTTP status: 503 Service Unavailable
