### ISSUE TITLE
Latest master tag fails

### ISSUE THREAD

**Issue by PaulWoitaschek** [cycneuramus/signal-aichat#19]
When starting conversations with the image:
`image: ghcr.io/cycneuramus/signal-aichat:master`

There is no response and in the logs I can see:

```
Traceback (most recent call last):

  File "/home/signal-aichat/signal-aichat.py", line 6, in <module>

    import ai

  File "/home/signal-aichat/ai.py", line 8, in <module>

    from EdgeGPT import Chatbot as Bing

ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (/home/signal-aichat/.local/lib/python3.10/site-packages/EdgeGPT/__init__.py)
```

**Comment by cycneuramus** [comment]
Ah, yes: those 3rd party API packages move extremely fast, and I haven't had the time to keep up (and probably won't for a while).

**Comment by PaulWoitaschek** [comment]
I have disabled it:

```
DEFAULT_MODEL=gpt
DISABLED_MODELS=bing bard hugchat llama
```

Right now the code is not working at all (I'm not doing anything with bing, I use openai)

**Comment by cycneuramus** [comment]
Right. Would probably have to make the relevant import statements conditional on a check for disabled models.

**Comment by PaulWoitaschek** [comment]
If the code isn't working shouldn't we remove it?

**Comment by PaulWoitaschek** [comment]
I suggest to pin the dependencies to have reproducible and functional builds.

**Comment by PaulWoitaschek** [comment]
I verified my PR and the gpt4 implementation is working. I also added pinning and some basic tests to reduce future regressions.
