### ISSUE TITLE
Error: I have no name!

### ISSUE THREAD

**Issue by p6002** [cycneuramus/signal-aichat#3]
My compose file:
https://pastebin.com/i46LQgBS
Commands:
`docker compose up -d signald`
`docker exec -it signal-aichat-signald /bin/bash
`
Result:
https://i.ibb.co/FXqLhRv/2023-05-09-183533.png

**Comment by p6002** [comment]
It seems to me that I should type the command inside the container:
`signaldctl account link --device-name signal-aichat`
I don't know how to do it, since it throws me out of the container.

**Comment by cycneuramus** [comment]
Sounds like the `signald` container can't manage to start properly due to some error. As to what the problem is exactly, you'll have to debug this for yourself, i.e. by checking the logs: `docker logs signal-aichat-signald -f`.

**Comment by p6002** [comment]
Ok, I thought I could test it on a group with friends. But I don't have the skills to fix it.
