### ISSUE TITLE
[ERROR] Processing message (139318381620712) by ai failed

### ISSUE THREAD

**Issue by p6002** [cycneuramus/signal-aichat#4]
I managed to install the bot. 
It was necessary to change the user in docker-compose from 1000:1000 to 0:0.
I added the phone number, connected via qr code. 
In .env I added api openai and default_model to gpt.
When I send a message from the same phone number on the group, the console shows:
```sh
signal-aichat-signald  | 18:03:25.187 [[redacted 33]9c4-receiver] INFO  manager-[redacted 33]9c4 - received sent message transcript from device 1
```
But no response appears in the chat.
When I text from another phone number, I get a message in the console:
```sh
signal-aichat-bot      | 2023-05-10 18:04:51,988 bot: [INFO] Chat context created for 0g7Ruz0qsQdUFDDUBP5dyVRhodjhmtgK2HX9U/hXyo=+17c52f31-605f-4fe2-862e-5f10e2a6f27e
signal-aichat-bot      | 2023-05-10 18:04:51,988 bot: [ERROR] Processing message (139858331620142) by ai failed
signal-aichat-bot      | Traceback (most recent call last):
signal-aichat-bot      |   File "/home/signal-aichat/.local/lib/python3.10/site-packages/semaphore/bot.py", line 128, in _handle_message
signal-aichat-bot      |     await func(context)
signal-aichat-bot      |   File "/home/signal-aichat/signal-aichat.py", line 52, in ai
signal-aichat-bot      |     ctx.data["bing"] = Chatbot(cookie_path="./cookies.json")
signal-aichat-bot      |   File "/home/signal-aichat/.local/lib/python3.10/site-packages/EdgeGPT.py", line 590, in __init__
signal-aichat-bot      |     self.cookies = json.load(f)
signal-aichat-bot      |   File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
signal-aichat-bot      |     return loads(fp.read(),
signal-aichat-bot      |   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
signal-aichat-bot      |     return _default_decoder.decode(s)
signal-aichat-bot      |   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
signal-aichat-bot      |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
signal-aichat-bot      |   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
signal-aichat-bot      |     raise JSONDecodeError("Expecting value", s, err.value) from None
signal-aichat-bot      | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cycneuramus** [comment]
It seems like you haven't set up Bing with the necessary cookies.

**Comment by p6002** [comment]
So Bing cookie in json is required, even if default_model=gpt? In that case, is llama also required to work?

It is possible to set the bot's response context when it receives the first message?

**Comment by cycneuramus** [comment]
The `KeyError` was a bug that I have hopefully [fixed](https://github.com/cycneuramus/signal-aichat/commit/f3632a0e6aad82ced6c711cca018910c966dd05f) now. 

About the Bing cookie, it's not great that currently you have to set it up even if you don't intend to use Bing or else the bot will crash. I'll try to make it possible to configure what models to enable/disable sometime in the coming days.

**Comment by p6002** [comment]
> I'll try to make it possible to configure what models to enable/disable sometime in the coming days.
That would be cool, I'll be waiting.

**Comment by p6002** [comment]
Thanks, bing started working and giving answers from internet (with a limit I guess) after couple messages:
`I encountered an error: sent 1000 (OK); then received 1000 (OK)`

GPT quotes and sends a message but only with an error:

`I encountered an error: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?`

**Comment by cycneuramus** [comment]
About Bing API limits, I actually don't know. The GPT error though is a bug that should be fixed now with v0.3.1.

**Comment by p6002** [comment]
l'll be waiting, it would also be nice to see the ability to change the language, or the ability to direct the bot with text like in the web version.

**Comment by cycneuramus** [comment]
Features like those would have to be implemented in the [library](https://github.com/acheong08/EdgeGPT/) I'm using. Though the bot will reply in whatever language your write to it, no?

**Comment by p6002** [comment]
Ok I'll take a peek at what you posted, because in addition to gpt bing can also be a useful assistant.
