### ISSUE TITLE
cookies.json mount is error prone

### ISSUE THREAD

**Issue by PaulWoitaschek** [cycneuramus/signal-aichat#7]
If you setup the volumes like that, and don't have the cookies.json file present, docker will create a cookies.json directory.

This is error prone and will cause confusions.

I suggest you to restructure it so that the `cookies.json` is in a `config` folder, i.e. `config/cookies.json`.
Then you'd bind this as `./config:....`

**Comment by cycneuramus** [comment]
Should be fixed in 0.3.2.
